name: SonarCloud Analysis


on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python Version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Run the python script
        working-directory: scripts
        run: python python.py

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Provided by GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}